name = "BraketSimulator"
uuid = "76d27892-9a0b-406c-98e4-7c178e9b3dff"
authors = ["Katharine Hyatt <hyatkath@amazon.com> and contributors"]
version = "0.0.1-DEV"

[deps]
Braket = "19504a0f-b47d-4348-9127-acc6cc69ef67"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[weakdeps]
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"
cuStateVec = "92f7fd98-d22e-4c0d-85a8-6ade11b672fb"

[extensions]
BraketSimulatorCuStateVecExt = "cuStateVec"
BraketSimulatorPythonExt = "PythonCall"

[compat]
Aqua = "=0.8"
Braket = "=0.8.2"
Combinatorics = "=1.0.2"
Dates = "1.6"
JSON3 = "=1.14.0"
LinearAlgebra = "1.6"
Logging = "1.6"
Pkg = "1.6"
PrecompileTools = "=1.2.1"
PythonCall = "=0.9.19"
Random = "1.6"
StaticArrays = "=1.9.3"
StatsBase = "=0.34.2"
Test = "1.6"
UUIDs = "1.6"
cuStateVec = "=1.2.0"
julia = "1.9"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test", "Logging", "PythonCall"]
